### ISSUE TITLE
prereqs are declared for the wrong phase(s)

### ISSUE THREAD

**Issue by karenetheridge** [DrHyde/perl-modules-Devel-CheckOS#16]
- since Devel::CheckOS loads itself in Makefile.PL, all its runtime prereqs (e.g. File::Find::Rule) need to be CONFIGURE_REQUIRES instead
- Test::* and File::Temp should be in TEST_REQUIRES, not PREREQ_PM
- please also list File::Spec and Exporter as CONFIGURE_REQUIRES dependencies at whatever version they need to be to supply the interfaces you are using

**Comment by wbraswell** [comment]
@DrHyde 
This is a very bad bug because it causes Catalyst not to install via CPAN!

**Comment by DrHyde** [comment]
Thanks. I've moved the 'use File::Find::Rule' and 'use File::Spec' back into an eval so they're only loaded when needed - and they're not needed in Makefile.PL. The fix will be on the CPAN shortly.

Splitting things out further into CONFIGURE_REQUIRES/TEST_REQUIRES/ELEPHANT_REQUIRES etc is not necessary and I won't add further complications like that unless there's an actual real-world problem.

File::Spec and Exporter version in core for any supported version of perl are good enough AFAIK.

**Comment by DrHyde** [comment]
@wbraswell should be fixed in 1.78, please can you confirm?

**Comment by wbraswell** [comment]
@DrHyde :+1: 
Yes it does appear to work now with v1.79 on CPAN!  :-)

**Comment by Grinnz** [comment]
Improper declaration of configure requires and test requires are real world problems. Configure requires must be specified for anything required to run Makefile.PL otherwise it will just die, which is a poor user experience (though it seems you solved this by other means). Any test requirement specified for the runtime or build phase will be installed when running cpanm --notest, which defeats half the purpose of --notest. Specifying prereqs properly is a simplification for the user, not a complication.

**Comment by DrHyde** [comment]
Patches welcome. I will apply a pointless but harmless pull request.

**Comment by DrHyde** [comment]
Errm, how did this break Catalyst? I don't see it in Catalyst's dependencies. Either there's a dependency somewhere that's not in META.{yml,json} or we've uncovered a bug in CPANdeps.

**Comment by wbraswell** [comment]
I am under the impression that Devel::CheckOS is a sub-sub-subdependency of Catalyst, which (according to co-author mst) "installs half of CPAN".  Sorry but I don't know exactly where in the dependency chain it lies, all I know is I typed `cpanm Task::Catalyst Catalyst::Devel` and it died somewhere along the way.

**Comment by DrHyde** [comment]
Ah-ha! Found the problem. It's pulled in by MooseX::Daemonize, which is an optional dependency of Catalyst::Devel, so doesn't show up in the dependency tree. So not much that can be done about it.

**Comment by wbraswell** [comment]
Okay great well at least we have solved the problem!  :-)
