### ISSUE TITLE
Support OS aliases

### ISSUE THREAD

**Issue by grr** [DrHyde/perl-modules-Devel-CheckOS#25]
Darwin and macOS (official name since 2016) should be aliases for MacOSX.

Also, to avoid having to always check the list of supported OS's to get the casing right, it would be helpful if it supported lowercased aliases.

**Comment by DrHyde** [comment]
It was never sold as Darwin, that's just an internal name (OK, and also the name of the open source underpinnings that no-one actually uses), but supporting MacOS as an alias is a good idea. I'll have to think about what is the best way of implementing it though.

Case-insensitive queries is also a good idea.

**Comment by DrHyde** [comment]
Assuming that it passes its tests, 07f17c4 will implement case-insensitive matching in the next release.

**Comment by DrHyde** [comment]
And aliases in [01e0f18](https://github.com/DrHyde/perl-modules-Devel-CheckOS/commit/01e0f18a57e7e19ab53bb3b91f78f9a0b5fe84c7)

**Comment by DrHyde** [comment]
Version 1.90 is on its way to the CPAN
