### ISSUE TITLE
Use TEST_REQUIRES for test dependencies instead of PREREQ_PM

### ISSUE THREAD

**Issue by ugexe** [DrHyde/perl-modules-Devel-CheckOS#27]
If possible it would be nice if e.g. `Test::Warnings` was listed as a TEST_REQUIRES instead of a PREREQ_PM so that `Devel::CheckOS` doesn't fail to install when testing is disabled.

**Comment by DrHyde** [comment]
Done in 1.93 which is on its way to the CPAN now.
